name: Destroy Portfolio Infrastructure

on:
  workflow_dispatch: {} # Permite acionamento manual na aba Actions

permissions:
  id-token: write
  contents: read

jobs:
  destroy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Delete SAM Backend Stack
        run: |
          echo "Iniciando a destruição da stack do backend..."
          aws cloudformation delete-stack \
            --stack-name portfolio-backend-contact \
            --region us-east-1
          
          aws cloudformation wait stack-delete-complete \
            --stack-name portfolio-backend-contact \
            --region us-east-1
          echo "Stack do backend destruída com sucesso!"